### ISSUE TITLE
[Feature Request] Monotonic timestamp to preserve order of logs in Baselime

### ISSUE THREAD

**Issue by mw10013** [baselime/edge-logger#10]
It seems multiple logs in a request appear in Baselime in an indeterminate order. This may be due to timestamps set to`Date.now()` and Cloudflare runtime returning the last I/O time for `Date.now()` (https://developers.cloudflare.com/workers/reference/security-model/#step-1-disallow-timers-and-multi-threading). This may cause many logs to have the same timestamp.

https://github.com/baselime/edge-logger/blob/7ed8b8f960a8ff0cba1ffd9d887ea1b9907f1c89/src/index.ts#L85-L92

Boris had this comment in slack about this.

```
 it's not possible within the Cloudflare runtime to have accurate time readings, as such it's possible that the logs come out of order or all with the same timestamp - it's a limitation of the edge runtime that we have to work with
```

Ask for a monotonic timestamp to preserve the order of logs in Baselime. We understand that a timestamp cannot be accurate on the Cloudflare runtime. Making them monotonic may seem to make them less accurate, but arguably more useful in practice.

In the screenshot below, the first set of logs use a monotonic timestamp while the second set uses `Date.now()`.

<img width="518" alt="Screenshot 2024-05-14 at 11 32 19 AM" src="https://github.com/baselime/edge-logger/assets/425584/ce7a2cc8-37ae-4cb9-826c-142b0570c1a1">

**Comment by Ankcorn** [comment]
It's live in 0.4.0 :)
